#!/usr/bin/env python3
"""Bounded Azure worker; default mode is an inert packet preview."""

import sys

sys.dont_write_bytecode = True

from atlas_azure_worker import main


if __name__ == "__main__":
    raise SystemExit(main())
