#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import shlex
import stat
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import harnesslib


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REGISTRY = ROOT / "ssot-projects.local.json"
HOOK_BEGIN = "# atlas-tools-ssot-begin"
HOOK_END = "# atlas-tools-ssot-end"


@dataclass(frozen=True)
class Project:
    path: Path
    harnesses: tuple[str, ...]


class EnforcementFailure(Exception):
    pass


def load_registry(path: Path) -> list[Project]:
    if not path.exists():
        raise EnforcementFailure(
            f"{path}: missing registry. Copy ssot-projects.example.json to {path.name} and edit it."
        )
    data = json.loads(path.read_text(encoding="utf-8"))
    raw_projects = data.get("projects")
    if not isinstance(raw_projects, list) or not raw_projects:
        raise EnforcementFailure(f"{path}: expected a non-empty projects list")

    manifest = harnesslib.load_manifest()
    projects: list[Project] = []
    for index, raw in enumerate(raw_projects, start=1):
        if isinstance(raw, str):
            raw = {"path": raw}
        if not isinstance(raw, dict):
            raise EnforcementFailure(f"{path}: project {index} must be an object or path string")
        if raw.get("skip"):
            continue
        project_path = raw.get("path")
        if not isinstance(project_path, str) or not project_path.strip():
            raise EnforcementFailure(f"{path}: project {index} is missing path")
        target = Path(os.path.expandvars(os.path.expanduser(project_path))).resolve()
        harnesses = normalize_harnesses(raw.get("harnesses"), target, manifest, path, index)
        projects.append(Project(target, harnesses))
    return projects


def normalize_harnesses(
    raw_harnesses: Any, target: Path, manifest: dict, registry_path: Path, index: int
) -> tuple[str, ...]:
    valid = set((manifest.get("adapters") or {}).keys())
    if raw_harnesses is None:
        detected = detect_harnesses(target, manifest)
        if detected:
            return tuple(detected)
        raise EnforcementFailure(
            f"{registry_path}: project {index} has no harnesses and none are installed at {target}"
        )
    if isinstance(raw_harnesses, str):
        harnesses = [raw_harnesses]
    elif isinstance(raw_harnesses, list):
        harnesses = raw_harnesses
    else:
        raise EnforcementFailure(f"{registry_path}: project {index} harnesses must be a string or list")
    normalized: list[str] = []
    for harness in harnesses:
        if not isinstance(harness, str) or harness not in valid:
            raise EnforcementFailure(
                f"{registry_path}: project {index} has invalid harness {harness!r}; expected one of {sorted(valid)}"
            )
        if harness not in normalized:
            normalized.append(harness)
    if not normalized:
        raise EnforcementFailure(f"{registry_path}: project {index} has an empty harnesses list")
    return tuple(normalized)


def detect_harnesses(target: Path, manifest: dict) -> list[str]:
    detected: list[str] = []
    for harness, adapter in (manifest.get("adapters") or {}).items():
        if (target / adapter["skills_path"]).exists() or (target / adapter["agents_path"]).exists():
            detected.append(harness)
    return detected


def check_project(project: Project) -> list[str]:
    if not project.path.exists():
        return [f"{project.path}: target does not exist"]
    return harnesslib.verify_harness_target(project.path, project.harnesses)


def repair_project(project: Project) -> list[Path]:
    changed: list[Path] = []
    for harness in project.harnesses:
        changed.extend(harnesslib.install_harness(harness, project.path))
    return changed


def managed_block(command: str) -> str:
    return (
        f"{HOOK_BEGIN}\n"
        "# Generated by AtlasMemory-Tools. Edit the SSOT repo, not generated harness copies.\n"
        f"{command}\n"
        f"{HOOK_END}\n"
    )


def strip_managed_block(existing: str) -> str:
    if HOOK_BEGIN in existing and HOOK_END in existing:
        before, rest = existing.split(HOOK_BEGIN, 1)
        _, after = rest.split(HOOK_END, 1)
        return before.rstrip() + "\n" + after.lstrip()
    return existing


def hook_insert_index(lines: list[str]) -> int:
    index = 0
    if lines and lines[0].startswith("#!"):
        index = 1
    while index < len(lines):
        stripped = lines[index].strip()
        if not stripped or stripped.startswith("set "):
            index += 1
            continue
        break
    return index


def replace_or_append_managed_block(existing: str, block: str) -> str:
    if not existing:
        return "#!/usr/bin/env sh\nset -eu\n\n" + block

    cleaned = strip_managed_block(existing).rstrip() + "\n"
    lines = cleaned.splitlines(keepends=True)
    index = hook_insert_index(lines)
    rendered = "".join(lines[:index]).rstrip() + "\n\n" + block + "\n" + "".join(lines[index:]).lstrip()
    return rendered.rstrip() + "\n"


def install_hook(path: Path, command: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    rendered = replace_or_append_managed_block(existing, managed_block(command))
    path.write_text(rendered, encoding="utf-8")
    current_mode = path.stat().st_mode
    path.chmod(current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def hook_path_for_repo(repo: Path, *, required: bool = True) -> Path | None:
    proc = subprocess.run(
        ["git", "-C", str(repo), "rev-parse", "--git-path", "hooks/pre-commit"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        if not required:
            return None
        message = (proc.stderr or proc.stdout or "not a git repository").strip()
        raise EnforcementFailure(f"{repo}: cannot resolve git hook path: {message}")
    hook_path = Path(proc.stdout.strip())
    if not hook_path.is_absolute():
        hook_path = repo / hook_path
    return hook_path.resolve()


def install_project_hook(project: Project) -> bool:
    hook_path = hook_path_for_repo(project.path, required=False)
    if hook_path is None:
        return False
    harness_args = " ".join(f"--harness {shlex.quote(harness)}" for harness in project.harnesses)
    command = (
        'repo_root="$(git rev-parse --show-toplevel)"\n'
        f"{shlex.quote(sys.executable)} {shlex.quote(str(ROOT / 'scripts' / 'verify_harness.py'))} "
        f'--target "$repo_root" {harness_args}'
    )
    install_hook(hook_path, command)
    return True


def install_canonical_hook() -> None:
    command = f"{shlex.quote(sys.executable)} {shlex.quote(str(ROOT / 'scripts' / 'verify_repo.py'))}"
    hook_path = hook_path_for_repo(ROOT)
    if hook_path is None:
        raise EnforcementFailure(f"{ROOT}: cannot resolve git hook path")
    install_hook(hook_path, command)


def print_project_header(project: Project) -> None:
    print(f"== {project.path}")
    print("harnesses: " + ", ".join(project.harnesses))


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Enforce AtlasMemory-Tools as the local SSOT for generated skills and agents."
    )
    parser.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY)
    parser.add_argument("--repair", action="store_true", help="Rewrite generated harness files from this SSOT.")
    parser.add_argument("--install-hooks", action="store_true", help="Install downstream pre-commit drift checks.")
    parser.add_argument("--install-canonical-hook", action="store_true", help="Install this repo's pre-commit verifier.")
    args = parser.parse_args()

    try:
        if args.install_canonical_hook:
            install_canonical_hook()
            print(f"installed canonical hook: {ROOT / '.git' / 'hooks' / 'pre-commit'}")
            if not (args.install_hooks or args.repair):
                return 0

        projects = load_registry(args.registry.resolve())

        failed = False
        for project in projects:
            print_project_header(project)
            if args.repair:
                changed = repair_project(project)
                print(f"rewrote {len(changed)} generated file(s)")
            if args.install_hooks:
                if install_project_hook(project):
                    print("installed downstream pre-commit hook")
                else:
                    print("skipped downstream pre-commit hook: target is not a git repository")
            errors = check_project(project)
            if errors:
                failed = True
                print("drift detected:")
                for error in errors:
                    print(f"- {error}")
            else:
                print("verified")
        return 1 if failed else 0
    except (EnforcementFailure, OSError, json.JSONDecodeError) as exc:
        print(f"enforce_local_ssot failed: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
